name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.1.1
  http: ^0.13.3
  flutter_spinkit: "^4.1.2"
  textfield_search: ^0.8.0
  auto_search: ^1.0.6
  enough_convert: ^1.3.0
  date_format: ^2.0.2
  weather_icons: ^3.0.0
  provider: ^6.0.1
  connectivity: ^0.4.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900
  - family: NotoSans
    fonts:
    
  
    - asset : fonts/NotoSansJP-Light.otf 
    - weight : 300
